<?xml version="1.0"?>
<robot name="skid_steer_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
 <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m * (3 * r * r + h * h) / 12}" ixy="0" ixz="0"
      iyy="${m * (3 * r * r + h * h) / 12}" iyz="0"
      izz="${m * r * r / 2}"
    />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m * (y * y + z * z) / 12}" ixy="0" ixz="0"
      iyy="${m * (x * x + z * z) / 12}" iyz="0"
      izz="${m * (x * x + z * z) / 12}"
    />
  </xacro:macro>
  
  <xacro:macro name="sphere_inertia" params="m r">
    <inertia ixx="${2 * m * r * r / 5}" ixy="0" ixz="0"
      iyy="${2 * m * r * r / 5}" iyz="0"
      izz="${2 * m * r * r / 5}"
    />
  </xacro:macro>

  <xacro:macro name="define_wheel" params="pos_fb pos_lr lr fb radius thickness mass">
    <link name="${pos_fb}_wheel_${pos_lr}">
        <inertial>
            <mass value="${mass}"/>
            <origin rpy="0 ${pi/2} ${pi/2}" xyz="0 0 0"/>
            <xacro:cylinder_inertia m="${mass}" r="${radius}" h="${thickness}" />
        </inertial>
        <collision>
            <origin rpy="0 ${pi/2} ${pi/2}" xyz="0 0 0"/>
            <geometry>
              <cylinder length="${thickness}" radius="${radius}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 ${pi/2} ${pi/2}" xyz="0 0 0"/>
            <geometry>
              <cylinder length="${thickness}" radius="${radius}"/>
            </geometry>
        </visual>
    </link>

    <joint name="${pos_fb}_wheel_${pos_lr}_hinge" type="continuous">
      <parent link="chassis"/>
      <child link="${pos_fb}_wheel_${pos_lr}"/>
      <origin xyz="${fb*chassis_length/2} ${lr*(thickness/2+chassis_breadth/2)} ${-(radius)}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
  </xacro:macro>
</robot>
