footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]]
otprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 1.0 #REDUCE THIS TO STOP COSTMAP2DROS TIMEOUT ERROR
transform_tolerance: 1.00

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 16.0

#layer definitions
static:
    map_topic: /irdc_mars
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /lidar, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
