#Configuation for robot odometry EKF
#
frequency: 50

two_d_mode: true
transform_time_offset: 10.0
publish_tf: false

yaw_offset: 0


odom_frame: odom
base_link_frame: base_link
world_frame: map
map_frame: map

odom0: /noisy_odom
odom0_config: [false, false, false, 
               false, false, false, 
               true,  true,  false, 
               false, false, true,
               false, false, false]
odom0_relative: false


imu0: /imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true,  false, false]
imu0_differential: false
imu0_relative: true

odom1: /odometry/wheel_imu_gps
odom1_config: [true, true,  false,
              false, false, false,
              false, false, false,
              false, false, true,
              false, false, false]
odom1_differential: false