obstacle_range: 0.5
raytrace_range: 0.5
footprint: [[0.4,0.3],[-0.4,0.3],[-0.4,-0.3],[0.4,-0.3]]
#robot_radius: ir_of_robot
inflation_radius: 0.4


origin_x: -21.649988
origin_y: -11.762978
origin_z: 0.0 

publish_frequency: 1.0


transform_tolerance: 1

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /lidar, marking: true, clearing: true, inf_is_valid: true, expected_update_rate: 0.2}

point_cloud_sensor: {sensor_frame: rs200_camera, data_type: PointCloud2, topic: /r200/camera/depth_registered/points, marking: true, clearing: true}
